### ISSUE TITLE
Create ISO XML for Pacific Islands Data.

### ISSUE THREAD

**Issue by dblodgett-usgs** [wdwatkins/gdp_sb#1]
Starting here: https://cida.usgs.gov/thredds/catalog.html There is a dataset called "Dynamical Downscaled and Projected Climate for the Pacific Islands" about half way down. Pull down each of the four main dataset's ISO xml.

This dataset's ISO metadata is a good reference: https://www.sciencebase.gov/catalog/item/54dd5e3de4b08de9379b38f9?community=Geo+Data+Portal+Catalog

Generally, there are four sections to these metadata records.
1) a bunch of elements at the top that pertain to the metadata record its self.
2) a MD_DataIdentification section that describes the dataset overall.
3) a set of SV_ServiceIdentification sections, one per OPeNDAP endpoint.
4) a distribution info section used for web resources meant for humans.

The four ISO records from the Pacific Islands data need to get compiled into a single record following this pattern. One that's done, check the file into the sb_iso folder of the pysb_gdp_iso repository in stash as a PR for review.

**Comment by wdwatkins** [comment]
@dblodgett-usgs at what level of tags should things be merged for the different files?

ie here: 
```
<gmd:fileIdentifier>
      <gco:CharacterString>cida.usgs.gov/kauai</gco:CharacterString>                                               
   </gmd:fileIdentifier>
```

Does there need to be separate `gmd:fileIdentifier` tags all four files (guam, oahu, etc), or can they all be put inside one?

**Comment by dblodgett-usgs** [comment]
This record is a good template. https://www.sciencebase.gov/catalog/item/566bcc01e4b09cfe53ca59a0?community=Geo+Data+Portal+Catalog

Take a look at that iso. Each of the spatial domains will be in it's own 'serviceIdentification' block and all four will be in one iso record with one 'dataIdentification' block.

**Comment by wdwatkins** [comment]
The data for all four islands will be in a single file then?

**Comment by dblodgett-usgs** [comment]
Yeppers. Four opendap services referenced from one metadata record.

**Comment by wdwatkins** [comment]
yeah, I hadn't made the connection that the fileIdentifier tag was referring to the ISO file itself, thought it was referring to an actual data file 🙄

**Comment by dblodgett-usgs** [comment]
Right. All the stuff outside the dataIdentification tags more or less refers to the metadata itself.

**Comment by dblodgett-usgs** [comment]
👍  on the stash PR. This task seems done to me.
