### ISSUE TITLE
Create ScienceBase Record for Pacific Islands data.

### ISSUE THREAD

**Issue by dblodgett-usgs** [wdwatkins/gdp_sb#2]
In your personal sciencebase space or as a private item in the GDP, create a new empty sciencebase record. Set the fileIdentifier at the top of the new metadata to the id of the sciencebase record.

Add the a new dataset's sciencebase id to gdp_web here: https://github.com/USGS-CIDA/gdp_web/blob/master/src/main/webapp/WEB-INF/jsp/algorithms.json
Allow access to
 "gov.usgs.cida.gdp.wps.algorithm.FeatureWeightedGridStatisticsAlgorithm" and "gov.usgs.cida.gdp.wps.algorithm.FeatureCoverageOPeNDAPIntersectionAlgorithm" only.

Add the iso xml to the sciencebase record and make sure things get rendered correctly.

**Comment by wdwatkins** [comment]
https://github.com/USGS-CIDA/gdp_web/pull/141

**Comment by wdwatkins** [comment]
@dblodgett-usgs I moved the sb item into the GDP Catalog https://www.sciencebase.gov/catalog/item/58581788e4b0e40e53c237c6.  What else needs to be added there?

**Comment by dblodgett-usgs** [comment]
I noticed that there is an error in the console when you load the GDP that talks about a null field. I removed all the rows with 'nilReason' and the record works now. I think it's one of the nill organization rows in one of the contact blocks. The file that is in the sciencebase record now works.

This screenshot shows what it looks like. We should add one more distribution info link that goes to the main thredds catalog so it shows up like the 'Daily Statistically Downscaled Climate Projections for the US and southern Canada east of the Rocky Mountains.' dataset when you click on it's tile. I think the GDP ui just shows the first distribution info link, so adding that one above the four that are in there should work. Other than that, I think we are good to go.

![screen shot 2016-12-21 at 2 36 28 pm](https://cloud.githubusercontent.com/assets/1492803/21405296/e83143fe-c78a-11e6-87f7-0782c8495a26.png)

**Comment by dblodgett-usgs** [comment]
pr with needed changes over here: https://internal.cida.usgs.gov/stash/projects/GDP/repos/sb_gdp_catalog/pull-requests/20/overview

That version is on ScienceBase.

**Comment by dblodgett-usgs** [comment]
We are so close, I'm going to go ahead and push this across the finish line.

**Comment by dblodgett-usgs** [comment]
Released GDP_WEB project at version 18 and pushed to qa and prod.
