### ISSUE TITLE
Remove wrf attributes from pacific islands dataset.

### ISSUE THREAD

**Issue by dblodgett-usgs** [wdwatkins/gdp_sb#4]
We need to remove all the global attributes associated with in the OPeNDAP services associated with the Pacific Islands dataset to help avoid confusion. 

To do this, we need to create a line like: 
```
<remove type="attribute" name="ISOILWATER"/>
```
for each of the all-capital-letter global attributes in each of the four Pacific Islands datasets. Each dataset should be able to use the same set of remove statements, but a script to create these might be the way to go in which case each dataset could be done seperately in case they have different lists.

The results should end up in the files here: https://internal.cida.usgs.gov/stash/projects/GDP/repos/thredds-config/browse/content/thredds/metadata/pacis

**Comment by wdwatkins** [comment]
What does this do that is different than just deleting the corresponding nodes from the ncml files?

**Comment by dblodgett-usgs** [comment]
These attributes aren't being created in ncml, so there isn't really an ncml node to be deleted. They are coming out of the underlying files. This 'remove' tag tells THREDDS to take the attribute out of the dataset that it exposes. I'd prefer to leave them in the underlying files in case someone comes along and cares about them when they download the actual files.
